/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRoiRouteImport } from './routes/_app.roi'
import { Route as AppProfitRouteImport } from './routes/_app.profit'
import { Route as AppFbaRouteImport } from './routes/_app.fba'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoiRoute = AppRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AppRoute,
} as any)
const AppProfitRoute = AppProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AppRoute,
} as any)
const AppFbaRoute = AppFbaRouteImport.update({
  id: '/fba',
  path: '/fba',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/fba': typeof AppFbaRoute
  '/profit': typeof AppProfitRoute
  '/roi': typeof AppRoiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/fba': typeof AppFbaRoute
  '/profit': typeof AppProfitRoute
  '/roi': typeof AppRoiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fba': typeof AppFbaRoute
  '/_app/profit': typeof AppProfitRoute
  '/_app/roi': typeof AppRoiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/dashboard' | '/fba' | '/profit' | '/roi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/fba' | '/profit' | '/roi'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/fba'
    | '/_app/profit'
    | '/_app/roi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roi': {
      id: '/_app/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof AppRoiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profit': {
      id: '/_app/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof AppProfitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fba': {
      id: '/_app/fba'
      path: '/fba'
      fullPath: '/fba'
      preLoaderRoute: typeof AppFbaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppFbaRoute: typeof AppFbaRoute
  AppProfitRoute: typeof AppProfitRoute
  AppRoiRoute: typeof AppRoiRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppFbaRoute: AppFbaRoute,
  AppProfitRoute: AppProfitRoute,
  AppRoiRoute: AppRoiRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
